fix: Add limits.h for PATH_MAX in redis_consumer.c
Alpine Linux fortified stdlib.h requires PATH_MAX to be defined.
Added #include <limits.h> before yyjson.h to provide PATH_MAX definition.

Error: PATH_MAX unset. A fortified realpath will not work.

This fixes the processor build on Alpine Linux.